// app/disclaimer/page.js
import Link from "next/link";

export const metadata = {
  title: "Disclaimer | PDFToolify",
  description:
    "Read the disclaimer for PDFToolify's online PDF tools and services.",
  openGraph: {
    title: "Disclaimer | PDFToolify",
    description:
      "Read the disclaimer for PDFToolify's online PDF tools and services.",
    type: "website",
    url: "https://pdftoolify.com/disclaimer",
  },
  twitter: {
    card: "summary_large_image",
    title: "Disclaimer | PDFToolify",
    description:
      "Read the disclaimer for PDFToolify's online PDF tools and services.",
  },
  alternates: {
    canonical: "https://pdftoolify.com/disclaimer",
  },
};

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-white py-16 px-4 sm:px-6 lg:px-8">
      <article className="mx-auto max-w-3xl">
        <h1 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
          Disclaimer
        </h1>
        <p className="mt-4 text-sm text-gray-500">
          Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
        </p>

        <div className="mt-8 space-y-8 text-gray-700">
          <section>
            <p>
              This disclaimer applies to your use of{" "}
              <strong>pdftoolify.com</strong> and the online PDF tools
              provided by <strong>PDFToolify</strong>. By using this website,
              you acknowledge and agree to the terms outlined below.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900">1. General information</h2>
            <p className="mt-3">
              The tools and content on this website are provided for general
              information and convenience purposes only. We make no guarantees
              about the completeness, accuracy, reliability, or suitability of
              the service for any particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900">2. No legal or professional advice</h2>
            <p className="mt-3">
              Nothing on this website constitutes legal, financial, or
              professional advice. The output generated by our PDF tools
              should not be relied upon as a substitute for advice from a
              qualified professional.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900">3. File processing</h2>
            <p className="mt-3">
              PDFToolify processes files temporarily to deliver the requested
              output.we are not responsible for any loss, corruption, or unauthorized
              access to files uploaded to or processed by the service. You
              are solely responsible for keeping backups of your original files.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900">4. Third-party links</h2>
            <p className="mt-3">
              Our website may contain links to third-party websites or
              services. We do not control and are not responsible for the
              content, policies, or practices of any third-party websites.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900">5. Limitation of liability</h2>
            <p className="mt-3">
              To the fullest extent permitted by applicable law, PDFToolify and
              its operators shall not be liable for any direct, indirect,
              incidental, special, or consequential damages arising from your
              use of, or inability to use, the service or any content on it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900">6. Changes to this disclaimer</h2>
            <p className="mt-3">
              We may update this disclaimer from time to time. The latest
              version will always be available on this page with a revised
              &quot;Last updated&quot; date. Continued use of the service means you
              accept the updated disclaimer.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900">7. Contact us</h2>
            <p className="mt-3">
              If you have any questions about this disclaimer, please contact us
              at{" "}
              <Link
                href="mailto:support@pdftoolify.com"
                className="font-medium text-blue-600 hover:underline"
              >
                support@pdftoolify.com
              </Link>
              .
            </p>
          </section>

          <section className="rounded-md bg-gray-50 p-4 text-sm text-gray-600">
            <p>
              <strong>Important:</strong> This disclaimer is provided by
              PDFToolify to explain the limits of our service and
              responsibility. It is not legal advice. For guidance specific to
              your situation, please consult a qualified legal professional.
            </p>
          </section>
        </div>

        <div className="mt-12 border-t border-gray-200 pt-8">
          <Link
            href="/"
            className="text-sm font-medium text-blue-600 hover:underline"
          >
            &larr; Back to home
          </Link>
        </div>
      </article>
    </main>
  );
}
